# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('seats_booked', models.PositiveSmallIntegerField(help_text="1 dan ko'p bo'lishi kerak va yo'lovdagi bo'sh o'rinlardan oshmasligi kerak.", verbose_name="Band qilingan o'rinlar")),
                ('price_per_seat', models.DecimalField(decimal_places=2, help_text="Buyurtma yaratilgan paytdagi narx. Yo'lov narxi o'zgarsa ham o'zgarmaydi.", max_digits=12, verbose_name="Bir o'rin narxi (nusxa)")),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='seats_booked * price_per_seat', max_digits=12, verbose_name='Umumiy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('driver_arrived', 'Haydovchi keldi'), ('in_progress', "Yo'lga chiqdi"), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi'), ('cancelled_by_passenger', "Yo'lovchi bekor qildi"), ('cancelled_by_driver', 'Haydovchi bekor qildi'), ('no_show', "Yo'lovchi kelmadi")], db_index=True, default='pending', max_length=32, verbose_name='Holat')),
                ('passenger_note', models.CharField(blank=True, default='', help_text='Buyurtma qilishda yozilgan izoh.', max_length=500, verbose_name="Yo'lovchi izohi")),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Bekor qilish sababi')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqti')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Familiya')),
                ('phone_number', models.CharField(blank=True, default='', help_text='+998901234567', max_length=20, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': "Buyurtma yo'lovchisi",
                'verbose_name_plural': "Buyurtma yo'lovchilari",
                'ordering': ('id',),
            },
        ),
    ]
