# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lovchi"),
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(help_text="Buyurtma qaysi yo'lovga berilganini ko'rsatadi.", on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='rides.drivertrip', verbose_name="Yo'lov"),
        ),
        migrations.AddField(
            model_name='orderpassenger',
            name='order',
            field=models.ForeignKey(help_text="Buyurtma o'chirilsa, birga sayohat qiluvchilar ham o'chadi (moliyaviy emas).", on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='orders.order', verbose_name='Buyurtma'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trip', 'status'], name='order_trip_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['passenger', 'status'], name='order_passenger_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_asc_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('seats_booked__gt', 0)), name='order_seats_booked_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_seat__gte', Decimal('0.00'))), name='order_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderpassenger',
            index=models.Index(fields=['order'], name='orderpassenger_order_idx'),
        ),
    ]
