# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('starts_at', models.DateTimeField(help_text='Faollik boshlanadigan payt (timezone-aware).', verbose_name='Boshlanish vaqti')),
                ('expires_at', models.DateTimeField(help_text='Faollik tugaydigan payt (timezone-aware).', verbose_name='Tugash vaqti')),
                ('status', models.CharField(choices=[('pending', "Kutilmoqda (to'lov kutilmoqda)"), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=20, verbose_name='Holat')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text="Reja narxi o'zgarsa ham, o'sha paytdagi to'lov saqlanib qoladi.", max_digits=12, verbose_name='Xarid qilingan narx')),
                ('auto_renew', models.BooleanField(default=False, help_text="To'lov muvaffaqiyatli bo'lsa muddat avtomatik uzaytiriladi.", verbose_name='Avtomatik yangilanish')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Faollashtirilgan vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqti')),
            ],
            options={
                'verbose_name': 'Haydovchi obunasi',
                'verbose_name_plural': 'Haydovchi obunalari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(help_text='Masalan: 1 oy, 3 oy, 6 oy.', max_length=120, unique=True, verbose_name='Nomi')),
                ('duration_days', models.PositiveIntegerField(help_text="Necha kunga mo'ljallangan. 30 kun = 1 oy, 365 kun = 1 yil.", verbose_name='Muddat (kun)')),
                ('price', models.DecimalField(decimal_places=2, help_text="So'mda. O'zgarishi mumkin - eski obunalar `price_at_purchase` saqlaydi.", max_digits=12, verbose_name='Narx')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Yangi xaridlarga taklif etiladi.', verbose_name='Faol')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text="Admin va bot ro'yxatidagi tartib.", verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Obuna rejası',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ('sort_order', 'duration_days'),
            },
        ),
    ]
