# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversubscription',
            name='driver',
            field=models.ForeignKey(help_text='Bir haydovchining obuna tarixi shu maydonda saqlanadi.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.driverprofile', verbose_name='Haydovchi'),
        ),
        migrations.AddField(
            model_name='driversubscription',
            name='payment',
            field=models.ForeignKey(blank=True, help_text="Obunani faollashtirgan to'lov (ixtiyoriy).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.payment', verbose_name="To'lov"),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'sort_order'], name='plan_active_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='plan_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='plan_price_non_negative'),
        ),
        migrations.AddField(
            model_name='driversubscription',
            name='plan',
            field=models.ForeignKey(help_text="Reja o'chirilmaydi - tarixiy obunalar butunligini saqlash uchun.", on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Reja'),
        ),
        migrations.AddIndex(
            model_name='driversubscription',
            index=models.Index(fields=['driver', 'status'], name='subscription_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='driversubscription',
            index=models.Index(fields=['status', 'expires_at'], name='subscription_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='driversubscription',
            index=models.Index(fields=['expires_at'], name='subscription_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='driversubscription',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='subscription_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='driversubscription',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_purchase__gte', Decimal('0.00'))), name='subscription_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='driversubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('driver',), name='uniq_active_subscription_per_driver'),
        ),
    ]
