# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('payment_type', models.CharField(choices=[('subscription', "Obuna to'lovi"), ('order', "Buyurtma to'lovi"), ('other', 'Boshqa')], db_index=True, default='subscription', max_length=20, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, help_text="So'mda. Manfiy bo'lishi mumkin emas.", max_digits=12, verbose_name='Summa')),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum'), ('cash', 'Naqd pul'), ('other', 'Boshqa')], db_index=True, default='click', max_length=20, verbose_name='Provayder')),
                ('external_transaction_id', models.CharField(blank=True, help_text="Provayder tomonidan berilgan ID. Bo'sh bo'lsa, hali to'lov yuborilmagan.", max_length=120, null=True, verbose_name='Tashqi tranzaksiya ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20, verbose_name='Holat')),
                ('paid_at', models.DateTimeField(blank=True, help_text="Faqat server tomonidan tasdiqlangan to'lovda to'ldiriladi.", null=True, verbose_name="To'langan vaqti")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provayder javobi (transaction id, status, summa va h.k.).', verbose_name="Qo'shimcha ma'lumot")),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Xatolik sababi')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan vaqti')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ('-created_at',),
            },
        ),
    ]
