# Generated by Django 5.2.6 on 2026-09-28 11:39

import apps.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(help_text='Masalan: Toshkent viloyati, Toshkent shahri, Samarqand viloyati.', max_length=120, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, default='', help_text='Ixtiyoriy tashqi kod (ixtiyoriy).', max_length=20, verbose_name='Kodi')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Faol bo'lmagan viloyat yangi manzil tanlashda ko'rinmaydi.", verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Viloyat / Shahar',
                'verbose_name_plural': 'Viloyat / Shaharlar',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_region_name_ci', violation_error_message='Bunday nomli viloyat allaqachon mavjud.')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(help_text='Masalan: Zangiota tumani, Sergeli tumani.', max_length=120, verbose_name='Nomi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.region', verbose_name='Viloyat / Shahar')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(help_text='Shahar, tuman markazi yoki MFY nomi. Masalan: Toshkent shahri, Chirchiq.', max_length=180, verbose_name='Nomi')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='-90 .. 90 orasida.', max_digits=9, validators=[apps.core.validators.validate_latitude], verbose_name='Kenglik (lat)')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='-180 .. 180 orasida.', max_digits=9, validators=[apps.core.validators.validate_longitude], verbose_name='Uzunlik (lng)')),
                ('address', models.CharField(blank=True, default='', help_text="Ko'cha, uy, mo'ljal. Ixtiyoriy.", max_length=255, verbose_name='Aniq manzil')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['district', 'is_active'], name='location_district_active_idx'), models.Index(fields=['name'], name='location_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('district', 'name'), name='uniq_location_name_per_district', violation_error_message='Bu tumanda bunday nomli manzil mavjud.'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='location_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='location_longitude_range')],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'is_active'], name='district_region_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uniq_district_name_per_region', violation_error_message='Bu viloyatda bunday nomli tuman mavjud.'),
        ),
    ]
