# Generated by Django 5.2.6 on 2026-09-28 11:39

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('brand', models.CharField(help_text='Lancia, Chevrolet, Hyundai ...', max_length=60, verbose_name='Brend')),
                ('model', models.CharField(help_text='Doblo, Nexia, Accent ...', max_length=60, verbose_name='Model')),
                ('color', models.CharField(help_text='Oq, qora, kumush ...', max_length=40, verbose_name='Rang')),
                ('plate_number', models.CharField(help_text="O'zbekiston davlat raqami, masalan: 01B 777AA.", max_length=15, unique=True, verbose_name='Davlat raqami')),
                ('year', models.PositiveSmallIntegerField(validators=[apps.core.validators.validate_vehicle_year, django.core.validators.MinValueValidator(1990)], verbose_name='Ishlab chiqarilgan yili')),
                ('seats_count', models.PositiveSmallIntegerField(default=4, help_text="Jami o'rindiq soni (haydovchi o'rni ham hisobga olinadi).", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name="O'rindiq soni")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Faol emas avtomobil bilan yo'lov yaratib bo'lmaydi.", verbose_name='Faol')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Administrator tomonidan tasdiqlangan. Faqat tasdiqlangan mashina ishlatiladi.', verbose_name='Tasdiqlangan')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti')),
                ('photo', models.ImageField(blank=True, help_text='Avtomobil rasmi (ixtiyoriy).', null=True, upload_to='vehicles/%Y/%m/', verbose_name='Rasm')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('driver', models.ForeignKey(help_text="Avtomobil egasi. Profil o'chirilsa avtomobil ham o'chirilmaydi.", on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='users.driverprofile', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['driver', 'is_active'], name='vehicle_driver_active_idx'), models.Index(fields=['driver', 'is_verified'], name='vehicle_driver_verified_idx'), models.Index(fields=['is_active', 'is_verified'], name='vehicle_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seats_count__gte', 1), ('seats_count__lte', 20)), name='vehicle_seats_count_range'), models.CheckConstraint(condition=models.Q(('year__gte', 1990)), name='vehicle_year_minimum')],
            },
        ),
    ]
