# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('score', models.DecimalField(decimal_places=2, help_text='0 dan 100 gacha.', max_digits=5, verbose_name='Ball')),
                ('time_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vaqt bali')),
                ('price_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Narx bali')),
                ('rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Reyting bali')),
                ('subscription_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Obuna bali')),
                ('vehicle_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avtomobil bali')),
                ('minutes_difference', models.IntegerField(default=0, help_text="So'rov oynaning boshlanishi va yo'lov chuqishi o'rtasidagi farq.", verbose_name='Vaqt farqi (daqiqa)')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, help_text="Yo'lov narxi - so'rovdagi maksimal narx (manfiy = qimmatroq emas).", max_digits=12, verbose_name='Narx farqi')),
                ('reason', models.CharField(choices=[('new_match', 'Yangi moslik'), ('rescore', 'Qayta baholash'), ('seats_changed', "O'rinlar o'zgardi"), ('reactivated', 'Qayta faollashtirildi')], default='new_match', max_length=20, verbose_name='Sabab')),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text="Shu so'rov bo'yicha reytingdagi o'rni (1 - eng yaxshi).", verbose_name="O'rin")),
            ],
            options={
                'verbose_name': 'Moslik',
                'verbose_name_plural': 'Mosliklar',
                'ordering': ('-score', 'trip__departure_time', 'trip_id'),
            },
        ),
    ]
