# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmatch',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rides.passengerrequest', verbose_name="Yo'lovchi so'rovi"),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rides.drivertrip', verbose_name="Yo'lov"),
        ),
        migrations.AddIndex(
            model_name='tripmatch',
            index=models.Index(fields=['request', '-score'], name='match_request_score_idx'),
        ),
        migrations.AddIndex(
            model_name='tripmatch',
            index=models.Index(fields=['trip'], name='match_trip_idx'),
        ),
        migrations.AddIndex(
            model_name='tripmatch',
            index=models.Index(fields=['request', 'rank'], name='match_request_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripmatch',
            constraint=models.UniqueConstraint(fields=('request', 'trip'), name='uniq_match_per_request_trip'),
        ),
        migrations.AddConstraint(
            model_name='tripmatch',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='match_score_0_100'),
        ),
    ]
