# Generated by Django 5.2.6 on 2026-09-28 11:39

import apps.core.validators
import apps.users.managers
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, help_text="Telegram hisobining noyob raqami. Bo'sh bo'lishi mumkin (admin panel orqali yaratilgan hisoblar uchun).", null=True, unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(blank=True, default='', help_text="+998901234567 ko'rinishida saqlanadi.", max_length=20, validators=[apps.core.validators.validate_phone_number], verbose_name='Telefon raqami')),
                ('role', models.CharField(choices=[('passenger', "Yo'lovchi"), ('driver', 'Haydovchi'), ('both', "Yo'lovchi va haydovchi")], db_index=True, default='passenger', help_text="Platformadagi vazifa: yo'lovchi, haydovchi yoki ikkalasi.", max_length=20, verbose_name='Rol')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, help_text='Administrator tomonidan bloklangan foydalanuvchi.', verbose_name='Bloklangan')),
                ('language_code', models.CharField(default='uz', help_text='Foydalanuvchi interfeys tili (uz / ru / en).', max_length=10, verbose_name='Til kodi')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Foydalanuvchi bot bilan oxirgi marta muloqot qilgan payt.', null=True, verbose_name='Oxirgi faollik')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text="Administrator tomonidan tasdiqlangan. Tasdiqlanmagan haydovchi yo'lov yarata olmaydi.", verbose_name='Tasdiqlangan')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='1.00 dan 5.00 gacha. `apps.reviews` servisi baholarni qayta hisoblaydi.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Reyting')),
                ('rating_count', models.PositiveIntegerField(default=0, help_text="Reyting o'rtachasi hisoblangan baholar soni.", verbose_name='Baholar soni')),
                ('total_trips', models.PositiveIntegerField(default=0, help_text="Haydovchi tomonidan yaratilgan yo'lovlar soni.", verbose_name="Jami yo'lovlar")),
                ('completed_trips', models.PositiveIntegerField(default=0, help_text="Muvaffaqiyatli yakunlangan yo'lovlar soni.", verbose_name="Yakunlangan yo'lovlar")),
                ('cancelled_trips', models.PositiveIntegerField(default=0, help_text="Bekor qilingan yo'lovlar soni.", verbose_name="Bekor qilingan yo'lovlar")),
                ('bio', models.CharField(blank=True, default='', help_text="Yo'lovchilar ko'radigan qisqacha tavsif.", max_length=500, verbose_name='Izoh')),
                ('user', models.OneToOneField(help_text='Faqat DRIVER yoki BOTH roliga ega foydalanuvchilar profil yaratishi mumkin.', on_delete=django.db.models.deletion.PROTECT, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Haydovchi profili',
                'verbose_name_plural': 'Haydovchi profillari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='user_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['is_verified', '-rating'], name='driverprofile_verified_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', Decimal('1.00')), ('rating__lte', Decimal('5.00'))), name='driverprofile_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.CheckConstraint(condition=models.Q(('completed_trips__lte', models.F('total_trips'))), name='driverprofile_completed_lte_total'),
        ),
    ]
