# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('body', models.TextField(max_length=4000, verbose_name='Matn')),
                ('is_from_support', models.BooleanField(default=False, verbose_name="Qo'llab-quvvatlashdan")),
                ('attachment_url', models.URLField(blank=True, default='', verbose_name='Fayl havolasi')),
            ],
            options={
                'verbose_name': 'Murojaat xabari',
                'verbose_name_plural': 'Murojaat xabarlari',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('category', models.CharField(choices=[('payment', "To'lov"), ('subscription', 'Obuna'), ('ride', "Yo'lov"), ('verification', 'Tasdiqlash'), ('account', 'Akkaunt'), ('technical', 'Texnik'), ('other', 'Boshqa')], db_index=True, default='other', max_length=30, verbose_name='Kategoriya')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', "O'rtacha"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], db_index=True, default='normal', max_length=10, verbose_name='Ustuvorlik')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', "Ko'rib chiqilmoqda"), ('closed', 'Yopilgan')], db_index=True, default='open', max_length=15, verbose_name='Holati')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Telegram orqali yuborilgan va foydalanuvchining ismi ko'rsatilmasin.", verbose_name='Anonim murojaat')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar vaqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqti')),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash murojaati",
                'verbose_name_plural': "Qo'llab-quvvatlash murojaatlari",
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
    ]
