# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('departure_time', models.DateTimeField(db_index=True, help_text='Vaqt zonasi bilan (UTC) saqlanadigan chuqish vaqti.', verbose_name='Chuqish vaqti')),
                ('total_seats', models.PositiveSmallIntegerField(help_text="Yo'lovchilar uchun taklif etilgan umumiy o'rin soni.", verbose_name="Jami o'rinlar")),
                ('available_seats', models.PositiveSmallIntegerField(help_text="Hozirda band qilinmagan o'rinlar. 0 bo'lsa status avtomatik `full` ga o'tadi.", verbose_name="Bo'sh o'rinlar")),
                ('price_per_seat', models.DecimalField(decimal_places=2, help_text="So'mda. Buyurtmada narx nusxalanadi (snapshot).", max_digits=12, verbose_name="Bir o'rin narxi")),
                ('comment', models.CharField(blank=True, default='', help_text="Yo'lovchi uchun qo'shimcha ma'lumot.", max_length=500, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('full', "To'liq"), ('in_progress', "Yo'lga chiqdi"), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('expired', 'Muddati tugadi')], db_index=True, default='draft', max_length=20, verbose_name='Holat')),
            ],
            options={
                'verbose_name': "Haydovchi yo'lovi",
                'verbose_name_plural': "Haydovchi yo'lovlari",
                'ordering': ('departure_time', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PassengerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('passenger_count', models.PositiveSmallIntegerField(default=1, help_text="Kerakli o'rinlar soni (1 dan katta).", verbose_name="Yo'lovchilar soni")),
                ('max_price_per_seat', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh bo'lsa - narx cheklovi yo'q.", max_digits=12, null=True, verbose_name="Maksimal narx (bir o'rinka)")),
                ('departure_from', models.DateTimeField(db_index=True, help_text='Engerta gapida chuqish vaqti.', verbose_name='Chuqish (dan)')),
                ('departure_until', models.DateTimeField(db_index=True, help_text='Eng kechiktirilgan chuqish vaqti.', verbose_name='Chuqish (gacha)')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('matched', 'Moslashdi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('expired', 'Muddati tugadi')], db_index=True, default='active', max_length=20, verbose_name='Holat')),
            ],
            options={
                'verbose_name': "Yo'lovchi so'rovi",
                'verbose_name_plural': "Yo'lovchi so'rovlari",
                'ordering': ('-created_at',),
            },
        ),
    ]
