# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('rides', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='driver',
            field=models.ForeignKey(help_text="Yo'lovni e'lon qilgan haydovchi.", on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='users.driverprofile', verbose_name='Haydovchi'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_origin', to='locations.location', verbose_name='Qayerdan'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_destination', to='locations.location', verbose_name='Qayerga'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='vehicle',
            field=models.ForeignKey(help_text="Avtomobil haydovchining profili va tanlangan mashinasiga tegishli bo'lishi shart.", on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='Avtomobil'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests_as_origin', to='locations.location', verbose_name='Qayerdan'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests', to=settings.AUTH_USER_MODEL, verbose_name="Yo'lovchi"),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests_as_destination', to='locations.location', verbose_name='Qayerga'),
        ),
        migrations.AddIndex(
            model_name='drivertrip',
            index=models.Index(fields=['driver', 'status'], name='trip_driver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='drivertrip',
            index=models.Index(fields=['status', 'departure_time'], name='trip_status_departure_idx'),
        ),
        migrations.AddIndex(
            model_name='drivertrip',
            index=models.Index(fields=['from_location', 'to_location'], name='trip_route_idx'),
        ),
        migrations.AddIndex(
            model_name='drivertrip',
            index=models.Index(fields=['driver', '-created_at'], name='trip_driver_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gt', 0), ('total_seats__lte', 16)), name='trip_total_seats_positive'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__gte', 0)), name='trip_available_seats_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='trip_available_seats_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_seat__gte', Decimal('0.00'))), name='trip_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('from_location_id', models.F('to_location_id')), _negated=True), name='trip_locations_must_differ'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['status', '-created_at'], name='req_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['passenger', 'status'], name='req_passenger_status_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['from_location', 'to_location'], name='req_route_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['departure_from', 'departure_until'], name='req_departure_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('passenger_count__gt', 0)), name='passenger_request_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('departure_until__gt', models.F('departure_from'))), name='passenger_request_departure_window'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_location__isnull', False), models.Q(('from_location_id', models.F('to_location_id')), _negated=True)), name='passenger_request_locations_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('max_price_per_seat__isnull', True), ('max_price_per_seat__gte', Decimal('0.00')), _connector='OR'), name='passenger_request_max_price_non_negative'),
        ),
    ]
