# Generated by Django 5.2.6 on 2026-09-29 18:42

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('rides', '0002_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passengerrequest',
            name='passenger_request_locations_must_differ',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_address',
            field=models.CharField(blank=True, default='', help_text="2GIS qaytargan to'liq manzil. Masalan: Toshkent, Amir Temur ko'chasi, 12.", max_length=255, verbose_name='Aniq manzil'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_city_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_district_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan kenglik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_latitude], verbose_name='Kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan uzunlik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_longitude], verbose_name='Uzunlik (lng)'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_place_name',
            field=models.CharField(blank=True, default='', help_text='2GIS obyekti nomi yoki kvartal nomi.', max_length=180, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='from_region_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Viloyat / shahar'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_address',
            field=models.CharField(blank=True, default='', help_text="2GIS qaytargan to'liq manzil. Masalan: Toshkent, Amir Temur ko'chasi, 12.", max_length=255, verbose_name='Aniq manzil'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_city_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_district_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan kenglik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_latitude], verbose_name='Kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan uzunlik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_longitude], verbose_name='Uzunlik (lng)'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_place_name',
            field=models.CharField(blank=True, default='', help_text='2GIS obyekti nomi yoki kvartal nomi.', max_length=180, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='to_region_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Viloyat / shahar'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_address',
            field=models.CharField(blank=True, default='', help_text="2GIS qaytargan to'liq manzil. Masalan: Toshkent, Amir Temur ko'chasi, 12.", max_length=255, verbose_name='Aniq manzil'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_city_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_district_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan kenglik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_latitude], verbose_name='Kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan uzunlik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_longitude], verbose_name='Uzunlik (lng)'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_place_name',
            field=models.CharField(blank=True, default='', help_text='2GIS obyekti nomi yoki kvartal nomi.', max_length=180, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='from_region_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Viloyat / shahar'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_address',
            field=models.CharField(blank=True, default='', help_text="2GIS qaytargan to'liq manzil. Masalan: Toshkent, Amir Temur ko'chasi, 12.", max_length=255, verbose_name='Aniq manzil'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_city_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_district_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan kenglik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_latitude], verbose_name='Kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="2GIS yoki qurilmadan olingan uzunlik. Bo'sh bo'lishi mumkin.", max_digits=9, null=True, validators=[apps.core.validators.validate_longitude], verbose_name='Uzunlik (lng)'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_place_name',
            field=models.CharField(blank=True, default='', help_text='2GIS obyekti nomi yoki kvartal nomi.', max_length=180, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='to_region_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Viloyat / shahar'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text="Katalogdagi tayyor manzil. Xaritada belgilangan nuqta uchun bo'sh qoldiriladi.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_origin', to='locations.location', verbose_name='Qayerdan'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text="Katalogdagi tayyor manzil. Xaritada belgilangan nuqta uchun bo'sh qoldiriladi.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_destination', to='locations.location', verbose_name='Qayerga'),
        ),
        migrations.AlterField(
            model_name='passengerrequest',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text="Katalogdagi tayyor manzil. Xaritada belgilangan nuqta uchun bo'sh qoldiriladi.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests_as_origin', to='locations.location', verbose_name='Qayerdan'),
        ),
        migrations.AlterField(
            model_name='passengerrequest',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text="Katalogdagi tayyor manzil. Xaritada belgilangan nuqta uchun bo'sh qoldiriladi.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests_as_destination', to='locations.location', verbose_name='Qayerga'),
        ),
        migrations.AddIndex(
            model_name='drivertrip',
            index=models.Index(fields=['from_city_name', 'to_city_name'], name='trip_snapshot_cities_idx'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['from_city_name', 'to_city_name'], name='req_snapshot_cities_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('from_location_id__isnull', False), models.Q(('from_latitude__isnull', False), ('from_longitude__isnull', False)), _connector='OR'), name='trip_origin_endpoint_resolved'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('to_location_id__isnull', False), models.Q(('to_latitude__isnull', False), ('to_longitude__isnull', False)), _connector='OR'), name='trip_destination_endpoint_resolved'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_latitude__isnull', True), ('from_longitude__isnull', True)), models.Q(('from_latitude__isnull', False), ('from_longitude__isnull', False)), _connector='OR'), name='trip_from_coordinates_are_both_set'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('from_latitude__isnull', True), models.Q(('from_latitude__gte', -90), ('from_latitude__lte', 90)), _connector='OR'), name='trip_from_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('from_longitude__isnull', True), models.Q(('from_longitude__gte', -180), ('from_longitude__lte', 180)), _connector='OR'), name='trip_from_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_latitude__isnull', True), ('to_longitude__isnull', True)), models.Q(('to_latitude__isnull', False), ('to_longitude__isnull', False)), _connector='OR'), name='trip_to_coordinates_are_both_set'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('to_latitude__isnull', True), models.Q(('to_latitude__gte', -90), ('to_latitude__lte', 90)), _connector='OR'), name='trip_to_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='drivertrip',
            constraint=models.CheckConstraint(condition=models.Q(('to_longitude__isnull', True), models.Q(('to_longitude__gte', -180), ('to_longitude__lte', 180)), _connector='OR'), name='trip_to_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_location_id__isnull', True), ('to_location_id__isnull', True), models.Q(('from_location_id', models.F('to_location_id')), _negated=True), _connector='OR'), name='passenger_request_locations_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_location_id__isnull', False), models.Q(('from_latitude__isnull', False), ('from_longitude__isnull', False)), _connector='OR'), name='passenger_request_origin_resolved'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_location_id__isnull', False), models.Q(('to_latitude__isnull', False), ('to_longitude__isnull', False)), _connector='OR'), name='passenger_request_destination_resolved'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_latitude__isnull', True), ('from_longitude__isnull', True)), models.Q(('from_latitude__isnull', False), ('from_longitude__isnull', False)), _connector='OR'), name='passenger_request_from_coordinates_are_both_set'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_latitude__isnull', True), models.Q(('from_latitude__gte', -90), ('from_latitude__lte', 90)), _connector='OR'), name='passenger_request_from_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_longitude__isnull', True), models.Q(('from_longitude__gte', -180), ('from_longitude__lte', 180)), _connector='OR'), name='passenger_request_from_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_latitude__isnull', True), ('to_longitude__isnull', True)), models.Q(('to_latitude__isnull', False), ('to_longitude__isnull', False)), _connector='OR'), name='passenger_request_to_coordinates_are_both_set'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_latitude__isnull', True), models.Q(('to_latitude__gte', -90), ('to_latitude__lte', 90)), _connector='OR'), name='passenger_request_to_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='passengerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_longitude__isnull', True), models.Q(('to_longitude__gte', -180), ('to_longitude__lte', 180)), _connector='OR'), name='passenger_request_to_longitude_range'),
        ),
    ]
