# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 dan 5 gacha butun son.', verbose_name='Baho')),
                ('comment', models.TextField(blank=True, default='', max_length=1000, verbose_name='Izoh')),
                ('order', models.ForeignKey(help_text='Faqat yakunlangan buyurtmalar baholanadi.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
