# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('type', models.CharField(choices=[('new_order', 'Yangi buyurtma'), ('order_accepted', 'Buyurtma qabul qilindi'), ('order_rejected', 'Buyurtma rad etildi'), ('trip_cancelled', "Yo'lov bekor qilindi"), ('subscription_expiring', 'Obuna tugashiga yaqin'), ('subscription_expired', 'Obuna muddati tugadi'), ('payment_success', "To'lov muvaffaqiyatli"), ('payment_failed', "To'lov muvaffaqiyatsiz"), ('new_message', 'Yangi xabar'), ('system', 'Tizim xabari')], db_index=True, default='system', max_length=30, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(blank=True, default='', max_length=1000, verbose_name='Matn')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qildi")),
                ('sent_at', models.DateTimeField(blank=True, help_text="Telegram (yoki boshqa kanal) orqali yuborilgan vaqt. Bo'sh bo'lsa yuborilmagan.", null=True, verbose_name='Yuborilgan vaqti')),
                ('is_sent', models.BooleanField(db_index=True, default=False, help_text='Yetkazib berish tizimi ushlu qilib yuborgan deb belgilagan.', verbose_name='Yuborilgan')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
