# Generated by Django 5.2.6 on 2026-09-28 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text="Telegram ga yuborish urinishlari. Maksimal urinishlar soni oshgandan keyin bildirishnoma 'berilgan' deb hisoblanadi va qayta yuborilmaydi.", verbose_name='Urinishlar soni'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.CharField(blank=True, default='', help_text='Yetkazib berishdagi oxirgi xato matni (diagnostika uchun).', max_length=255, verbose_name='Oxirgi xato'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent', 'attempts'], name='notif_sent_attempts_idx'),
        ),
    ]
