# Generated by Django 5.2.6 on 2026-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_attempts_notification_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Foydalanuvchi bildirishnomani birinchi marta ochgan vaqt.', null=True, verbose_name="O'qilgan vaqti"),
        ),
    ]
