# Generated by Django 5.2.6 on 2026-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('type', models.CharField(choices=[('text', 'Matn'), ('system', 'Tizim'), ('location', 'Manzil')], default='text', max_length=10, verbose_name='Turi')),
                ('text', models.TextField(blank=True, default='', max_length=2000, verbose_name='Matn')),
                ('is_read', models.BooleanField(default=False, help_text="Xabarni yuboruvchidan tashqari birinchi o'quvchi tomonidan o'qilgan.", verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Yozma yaratilgan payt (UTC, vaqt zonasi bilan).', verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yozma oxirgi marta yangilangan payt (UTC, vaqt zonasi bilan).', verbose_name='Yangilangan vaqti')),
                ('last_message_at', models.DateTimeField(blank=True, help_text="Ro'yxatni tez tartibga solish va 'yangi xabar' belgisini hisoblash uchun.", null=True, verbose_name='Oxirgi xabar vaqti')),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=120, verbose_name="Oxirgi xabar ko'rinishi")),
                ('is_closed', models.BooleanField(default=False, help_text='Yakunlangan yoki bekor qilingan buyurtma chatini yopish uchun ishlatiladi.', verbose_name='Yopilgan')),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ('-last_message_at', '-created_at'),
            },
        ),
    ]
