# Generated by Django 5.2.6 on 2026-09-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='orders.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread', verbose_name='Suhbat'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['is_closed', '-last_message_at'], name='chat_closed_last_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'id'], name='chatmsg_thread_id_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'is_read'], name='chatmsg_thread_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='chatmsg_sender_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), ('type', 'location'), _connector='OR'), name='chatmsg_text_required_unless_location'),
        ),
    ]
